CREATE DATABASE FACTURACION;
USE FACTURACION;
SET DATEFORMAT dmy;
--TABLA ARTICULOS
CREATE TABLE ARTICULOS(
COD_ARTICULO INT IDENTITY(1,1),
NOMBRE VARCHAR(40) NOT NULL,
PRE_UNITARIO DECIMAL(8,2) NOT NULL,
CANTIDAD INT NOT NULL,
ACTIVO BIT NOT NULL
CONSTRAINT PK__ARTICULO PRIMARY KEY(COD_ARTICULO)
);

/*
//////////////////////////////////////////////
//////////INSERTS TABLA ARTICULOS/////////////
/////////////////////////////////////////////
*/
DELETE FROM ARTICULOS;
SELECT * FROM ARTICULOS;
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pelota de Fútbol', 5599, 100, 1);--1
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Raqueta Tenis', 8950, 100, 1);--2
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pelota de Basket', 2975, 100, 1);--3
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Guantes de Boxeo', 3599, 100, 1);--4
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Tabla de Surf', 15900, 100, 1);--5
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Casco Ciclismo', 4550, 100, 1);--6
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Raqueta Squash', 3425, 100, 1);--7
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pantalones de Yoga', 2999, 100, 1)--8;
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pelota Voleibol', 2875, 100, 1);--9
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Cinta de Correr', 49900, 100, 1);--10
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Raqueta Bádminton', 3650, 100, 1);--11
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Guantes de Aqrquero', 2750, 100, 1);--12
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Patines', 5999, 100, 1);--13
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Mallas de Running', 6875, 100, 1);--14
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pelota de Rugby', 3225, 100, 1);--15
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Raqueta de Pádel', 6450, 100, 1);--16
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Soga para Saltar', 999, 100, 1);--17
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Cinta de Yoga', 1450, 100, 1);--18
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pelota Medicinal', 2875, 100, 1);--19
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Camiseta de Racing(cba)', 12199, 100, 1);--20
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Red de Tenis', 9250, 100, 1);--21
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Gorra de Natación', 3225, 100, 1);--22
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Balón de Fútbol Sala', 2299, 100, 1);--23
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Tablas de Esquí', 12900, 100, 1);--24
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Saco de Boxeo', 6950, 100, 1);--25
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Bicicleta de Montaña', 34900, 100, 1);--26
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pelotas de Golf', 5000, 100, 1);--27
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Mancuernas', 5450, 100, 1);--28
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Botella de Agua Deportiva', 2250, 100, 1);--29
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Rodillera Deportiva', 2000, 100, 1);--30
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Casaca de Ciclismo', 7000, 100, 1);--31
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Pelota de Cricket', 3000, 100, 1);--32
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Peto de Entrenamiento', 15000, 100, 1);--33
INSERT INTO ARTICULOS (NOMBRE, PRE_UNITARIO, CANTIDAD, ACTIVO) VALUES ('Tablero de Ajedrez', 5000, 100, 1);--34

--TABLA FORMA DE PAGO
CREATE TABLE FORMA_PAGOS(
COD_FPAGO INT IDENTITY(1,1),
DESCRIPCION VARCHAR(40) NOT NULL,
ACTIVO BIT NOT NULL,
CONSTRAINT PK_FPAGO PRIMARY KEY(COD_FPAGO)
);



/*
//////////////////////////////////////////////
/////////INSERTS TABLA FORMA_PAGOS////////////
/////////////////////////////////////////////
*/
INSERT INTO FORMA_PAGOS (DESCRIPCION, ACTIVO) VALUES(
'EFECTIVO', 1),--1
('TARJETA DEBITO', 1),--2
('TARJETA CREDITO',1);--3

--TABLA FACTURAS 
CREATE TABLE FACTURAS(
NRO_FACTURA INT IDENTITY(1,1),
FECHA DATETIME NOT NULL,
CLIENTE VARCHAR(90) NOT NULL,
MONTO DECIMAL(10,2) NOT NULL,
COD_F_PAGO INT NOT NULL,
DESCUENTO INT,
CONSTRAINT PK_FACTURA PRIMARY KEY(NRO_FACTURA),
CONSTRAINT FK_FACTURA_FPAGO FOREIGN KEY(COD_F_PAGO) REFERENCES FORMA_PAGOS(COD_FPAGO)
);

/*
//////////////////////////////////////////////
//////////INSERTS TABLA FACTURAS/////////////
/////////////////////////////////////////////
*/
INSERT INTO FACTURAS(FECHA, CLIENTE, MONTO, COD_F_PAGO, DESCUENTO) VALUES('28/08/2023', 'CONSUMIDOR FINAL', 6718.8, 1, 10);

--DETALLE DE FACTURAS 
CREATE TABLE DETALLE_FACTURAS(
NRO_DETALLE INT,
NRO_FACTURA INT NOT NULL,
COD_ARTICULO INT NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (NRO_DETALLE, NRO_FACTURA),
CONSTRAINT FK_DETALLE_ARTICULO FOREIGN KEY(COD_ARTICULO) REFERENCES ARTICULOS(COD_ARTICULO),
CONSTRAINT FK_DETALLE_MAESTRO FOREIGN KEY(NRO_FACTURA) REFERENCES FACTURAS(NRO_FACTURA)
);

/*
//////////////////////////////////////////////
//////INSERTS TABLA DETALLE_FACTURAS/////////
/////////////////////////////////////////////
*/
INSERT INTO DETALLE_FACTURAS(NRO_DETALLE, NRO_FACTURA, COD_ARTICULO, CANTIDAD) VALUES(
1, 1, 1, 1);

SELECT * FROM FACTURAS F
JOIN DETALLE_FACTURAS D ON F.NRO_FACTURA = D.NRO_FACTURA;

DELETE FROM FACTURAS;